/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.test.batch_teacher.Add_Batch_Teacher;
import com.test.batch_teacher.Delete_Batch_Teacher;
import com.test.batch_teacher.Show_Batch_Teacher;
import com.test.batch_teacher.Update_Batch_Teacher;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Mutaher Affan
 */
public class Batch_Teacher_Management extends javax.swing.JFrame {

    /**
     * Creates new form Batch_Teacher_Management
     */
    public Batch_Teacher_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        exit_Label = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        Delete_Batch_Teacher_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Show_Batch_Teacher_Panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Add_Batch_Teacher_Panel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Update_Batch_Teacher_Panel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(130, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Batch Teacher Management ");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_classroom_filled_50px_3.png"))); // NOI18N

        exit_Label.setForeground(new java.awt.Color(255, 255, 255));
        exit_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_LabelMousePressed(evt);
            }
        });

        minimize_label.setForeground(new java.awt.Color(255, 255, 255));
        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimize_labelMousePressed(evt);
            }
        });

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"))); // NOI18N
        Back_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Back_label)
                .addGap(150, 150, 150)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(0, 236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit_Label))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit_Label)
                            .addComponent(minimize_label))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14))
                    .addComponent(Back_label))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 230));

        Delete_Batch_Teacher_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_Batch_Teacher_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Delete_Batch_Teacher_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Delete_Batch_Teacher_PanelMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_delete_user_male_50px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Delete Batch Teacher");

        javax.swing.GroupLayout Delete_Batch_Teacher_PanelLayout = new javax.swing.GroupLayout(Delete_Batch_Teacher_Panel);
        Delete_Batch_Teacher_Panel.setLayout(Delete_Batch_Teacher_PanelLayout);
        Delete_Batch_Teacher_PanelLayout.setHorizontalGroup(
            Delete_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(75, 75, 75))
            .addGroup(Delete_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delete_Batch_Teacher_PanelLayout.setVerticalGroup(
            Delete_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Delete_Batch_Teacher_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 200, 140));

        Show_Batch_Teacher_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_Batch_Teacher_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Show_Batch_Teacher_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Show_Batch_Teacher_PanelMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_classroom_filled_50px_2.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 118, 232));
        jLabel16.setText("Show Batch Teachers");

        javax.swing.GroupLayout Show_Batch_Teacher_PanelLayout = new javax.swing.GroupLayout(Show_Batch_Teacher_Panel);
        Show_Batch_Teacher_Panel.setLayout(Show_Batch_Teacher_PanelLayout);
        Show_Batch_Teacher_PanelLayout.setHorizontalGroup(
            Show_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(75, 75, 75))
            .addGroup(Show_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Show_Batch_Teacher_PanelLayout.setVerticalGroup(
            Show_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Show_Batch_Teacher_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 140));

        Add_Batch_Teacher_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Batch_Teacher_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_Batch_Teacher_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_Batch_Teacher_PanelMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_add_administrator_filled_50px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 118, 232));
        jLabel18.setText("Add Batch Teacher");

        javax.swing.GroupLayout Add_Batch_Teacher_PanelLayout = new javax.swing.GroupLayout(Add_Batch_Teacher_Panel);
        Add_Batch_Teacher_Panel.setLayout(Add_Batch_Teacher_PanelLayout);
        Add_Batch_Teacher_PanelLayout.setHorizontalGroup(
            Add_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(75, 75, 75))
            .addGroup(Add_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Add_Batch_Teacher_PanelLayout.setVerticalGroup(
            Add_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Add_Batch_Teacher_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 200, 140));

        Update_Batch_Teacher_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_Batch_Teacher_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Update_Batch_Teacher_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Update_Batch_Teacher_PanelMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_available_updates_filled_50px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 118, 232));
        jLabel20.setText("Update Batch Teacher");

        javax.swing.GroupLayout Update_Batch_Teacher_PanelLayout = new javax.swing.GroupLayout(Update_Batch_Teacher_Panel);
        Update_Batch_Teacher_Panel.setLayout(Update_Batch_Teacher_PanelLayout);
        Update_Batch_Teacher_PanelLayout.setHorizontalGroup(
            Update_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(75, 75, 75))
            .addGroup(Update_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Update_Batch_Teacher_PanelLayout.setVerticalGroup(
            Update_Batch_Teacher_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Batch_Teacher_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Update_Batch_Teacher_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 200, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_LabelMousePressed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_exit_LabelMousePressed

    private void Delete_Batch_Teacher_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Batch_Teacher_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Delete_Batch_Teacher_Panel);
    }//GEN-LAST:event_Delete_Batch_Teacher_PanelMouseEntered

    private void Delete_Batch_Teacher_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Batch_Teacher_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Delete_Batch_Teacher_Panel);
    }//GEN-LAST:event_Delete_Batch_Teacher_PanelMouseExited

    private void Show_Batch_Teacher_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Batch_Teacher_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Show_Batch_Teacher_Panel);
    }//GEN-LAST:event_Show_Batch_Teacher_PanelMouseEntered

    private void Show_Batch_Teacher_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Batch_Teacher_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Show_Batch_Teacher_Panel);
    }//GEN-LAST:event_Show_Batch_Teacher_PanelMouseExited

    private void Add_Batch_Teacher_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Batch_Teacher_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Add_Batch_Teacher_Panel);
    }//GEN-LAST:event_Add_Batch_Teacher_PanelMouseEntered

    private void Add_Batch_Teacher_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Batch_Teacher_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Add_Batch_Teacher_Panel);
    }//GEN-LAST:event_Add_Batch_Teacher_PanelMouseExited

    private void Update_Batch_Teacher_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Batch_Teacher_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Update_Batch_Teacher_Panel);
    }//GEN-LAST:event_Update_Batch_Teacher_PanelMouseEntered

    private void Update_Batch_Teacher_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Batch_Teacher_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Update_Batch_Teacher_Panel);
    }//GEN-LAST:event_Update_Batch_Teacher_PanelMouseExited

    private void minimize_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMousePressed
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMousePressed

    private void Show_Batch_Teacher_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Batch_Teacher_PanelMouseClicked
        // TODO add your handling code here:
        Show_Batch_Teacher show_Batch_Teacher = new Show_Batch_Teacher();
        show_Batch_Teacher.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Show_Batch_Teacher_PanelMouseClicked

    private void Add_Batch_Teacher_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Batch_Teacher_PanelMouseClicked
        // TODO add your handling code here:
        Add_Batch_Teacher add_Batch_Teacher = new Add_Batch_Teacher();
        add_Batch_Teacher.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Add_Batch_Teacher_PanelMouseClicked

    private void Delete_Batch_Teacher_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Batch_Teacher_PanelMouseClicked
        // TODO add your handling code here:
        Delete_Batch_Teacher delete_Batch_Teacher = new Delete_Batch_Teacher();
        delete_Batch_Teacher.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Delete_Batch_Teacher_PanelMouseClicked

    private void Update_Batch_Teacher_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Batch_Teacher_PanelMouseClicked
        // TODO add your handling code here:
        Update_Batch_Teacher update_Batch_Teacher = new Update_Batch_Teacher();
        update_Batch_Teacher.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Update_Batch_Teacher_PanelMouseClicked

    private void Back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Back_labelMouseClicked

       //------------- SETTING UP COLORS -------------//
    
    public void setColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }
    
    public void resetColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(240,240,240));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch_Teacher_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch_Teacher_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch_Teacher_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch_Teacher_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batch_Teacher_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Batch_Teacher_Panel;
    private javax.swing.JLabel Back_label;
    private javax.swing.JPanel Delete_Batch_Teacher_Panel;
    private javax.swing.JPanel Show_Batch_Teacher_Panel;
    private javax.swing.JPanel Update_Batch_Teacher_Panel;
    private javax.swing.JLabel exit_Label;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize_label;
    // End of variables declaration//GEN-END:variables
}
