/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.test.student.Add_Student;
import com.test.student.Delete_Student;
import com.test.student.Show_Student;
import com.test.student.Update_Student;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Mutaher Affan
 */
public class Student_Management extends javax.swing.JFrame {

    /**
     * Creates new form Student_Management
     */
    public Student_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        exit_Label = new javax.swing.JLabel();
        minimize_Label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        Delete_Student_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Show_Student_Panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Add_Student_Panel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Update_Student_Panel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(130, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Student Management ");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_students_filled_50px_1.png"))); // NOI18N

        exit_Label.setForeground(new java.awt.Color(255, 255, 255));
        exit_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_LabelMousePressed(evt);
            }
        });

        minimize_Label.setForeground(new java.awt.Color(255, 255, 255));
        minimize_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimize_LabelMousePressed(evt);
            }
        });

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"))); // NOI18N
        Back_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Back_label)
                .addGap(204, 204, 204)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(0, 292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit_Label))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit_Label)
                            .addComponent(minimize_Label))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14))
                    .addComponent(Back_label))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 230));

        Delete_Student_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_Student_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Delete_Student_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Delete_Student_PanelMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_delete_user_male_50px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Delete Student");

        javax.swing.GroupLayout Delete_Student_PanelLayout = new javax.swing.GroupLayout(Delete_Student_Panel);
        Delete_Student_Panel.setLayout(Delete_Student_PanelLayout);
        Delete_Student_PanelLayout.setHorizontalGroup(
            Delete_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Student_PanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(77, 77, 77))
            .addGroup(Delete_Student_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delete_Student_PanelLayout.setVerticalGroup(
            Delete_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_Student_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Delete_Student_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 200, 140));

        Show_Student_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_Student_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Show_Student_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Show_Student_PanelMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_student_male_filled_50px.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 118, 232));
        jLabel16.setText("Show Student");

        javax.swing.GroupLayout Show_Student_PanelLayout = new javax.swing.GroupLayout(Show_Student_Panel);
        Show_Student_Panel.setLayout(Show_Student_PanelLayout);
        Show_Student_PanelLayout.setHorizontalGroup(
            Show_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_Student_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(71, 71, 71))
            .addGroup(Show_Student_PanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel16)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        Show_Student_PanelLayout.setVerticalGroup(
            Show_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_Student_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Show_Student_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 140));

        Add_Student_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Student_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_Student_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_Student_PanelMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_add_user_group_filled_50px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 118, 232));
        jLabel18.setText("Add Student");

        javax.swing.GroupLayout Add_Student_PanelLayout = new javax.swing.GroupLayout(Add_Student_Panel);
        Add_Student_Panel.setLayout(Add_Student_PanelLayout);
        Add_Student_PanelLayout.setHorizontalGroup(
            Add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Student_PanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(71, 71, 71))
            .addGroup(Add_Student_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Add_Student_PanelLayout.setVerticalGroup(
            Add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Student_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Add_Student_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 200, 140));

        Update_Student_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_Student_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Update_Student_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Update_Student_PanelMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_available_updates_filled_50px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 118, 232));
        jLabel20.setText("Update Student");

        javax.swing.GroupLayout Update_Student_PanelLayout = new javax.swing.GroupLayout(Update_Student_Panel);
        Update_Student_Panel.setLayout(Update_Student_PanelLayout);
        Update_Student_PanelLayout.setHorizontalGroup(
            Update_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Student_PanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(Update_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Student_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Student_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(47, 47, 47))))
        );
        Update_Student_PanelLayout.setVerticalGroup(
            Update_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Student_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Update_Student_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 200, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_LabelMousePressed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_exit_LabelMousePressed

    private void Delete_Student_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Student_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Delete_Student_Panel);
    }//GEN-LAST:event_Delete_Student_PanelMouseEntered

    private void Delete_Student_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Student_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Delete_Student_Panel);
    }//GEN-LAST:event_Delete_Student_PanelMouseExited

    private void Show_Student_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Student_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Show_Student_Panel);
    }//GEN-LAST:event_Show_Student_PanelMouseEntered

    private void Show_Student_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Student_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Show_Student_Panel);
    }//GEN-LAST:event_Show_Student_PanelMouseExited

    private void Add_Student_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Student_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Add_Student_Panel);
    }//GEN-LAST:event_Add_Student_PanelMouseEntered

    private void Add_Student_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Student_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Add_Student_Panel);
    }//GEN-LAST:event_Add_Student_PanelMouseExited

    private void Update_Student_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Student_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Update_Student_Panel);
    }//GEN-LAST:event_Update_Student_PanelMouseEntered

    private void Update_Student_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Student_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Update_Student_Panel);
    }//GEN-LAST:event_Update_Student_PanelMouseExited

    private void minimize_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_LabelMousePressed
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_LabelMousePressed

    private void Show_Student_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_Student_PanelMouseClicked
        // TODO add your handling code here:
        Show_Student show_Student = new Show_Student();
        show_Student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Show_Student_PanelMouseClicked

    private void Add_Student_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Student_PanelMouseClicked
        // TODO add your handling code here:
        Add_Student add_Student = new Add_Student();
        add_Student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Add_Student_PanelMouseClicked

    private void Delete_Student_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_Student_PanelMouseClicked
        // TODO add your handling code here:
        Delete_Student delete_Student = new Delete_Student();
        delete_Student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Delete_Student_PanelMouseClicked

    private void Update_Student_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_Student_PanelMouseClicked
        // TODO add your handling code here:
        Update_Student update_Student = new Update_Student();
        update_Student.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Update_Student_PanelMouseClicked

    private void Back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Back_labelMouseClicked

    //------------- SETTING UP COLORS -------------//
    
    public void setColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }
    
    public void resetColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(240,240,240));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Student_Panel;
    private javax.swing.JLabel Back_label;
    private javax.swing.JPanel Delete_Student_Panel;
    private javax.swing.JPanel Show_Student_Panel;
    private javax.swing.JPanel Update_Student_Panel;
    private javax.swing.JLabel exit_Label;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize_Label;
    // End of variables declaration//GEN-END:variables
}
